name: Install

on: [workflow_call, workflow_dispatch]

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml
    secrets: inherit

  install:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install
