name: Lanuch Turbo Remote Cache Server

on: [workflow_call, workflow_dispatch]

jobs:
  lanuch_turbo_remote_cache_server:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: Launch Turbo Remote Cache Server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
