name: 👷 Pull Requset CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_lint:
    uses: ./.github/workflows/checkLint.yml
    secrets: inherit

  check_type:
    uses: ./.github/workflows/checkType.yml
    secrets: inherit

  unit_test:
    uses: ./.github/workflows/unitTest.yml
    secrets: inherit

  test:
    if: always()
    runs-on: ubuntu-latest
    needs: [check_lint, check_type, unit_test]
    steps:
      - run: echo "${{ needs.check_lint.result== 'failure'}}"
      - run: echo "${{ needs.check_type.result== 'failure'}}"
      - run: echo "${{ needs.unit_test.result== 'failure' }}"

  ready_to_review:
    if: always()
    needs: [check_lint, check_type, unit_test]
    uses: ./.github/workflows/readyToReview.yml
    secrets: inherit
    with:
      has_failure: ${{ needs.check_lint.result == 'failure' || needs.check_type.result == 'failure' || needs.unit_test.result == 'failure' }}
