name: Ready To Review

on: [workflow_call, workflow_dispatch]

jobs:
  submitMessage:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          # Authetication token to access GitHub APIs. (Can be omitted by default.)
          github-token: ${{ github.token }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
          sha: ${{ github.event.pull_request.head.sha }}

      - run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"

      - name: formating body \r
        id: formating-r
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ steps.PR.outputs.pr_body }}
          find: "\r"
          replace: "\\r"

      - name: formating body \n
        id: formating-n
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ steps.formating-r.outputs.value }}
          find: "\n"
          replace: "\\n"

      - name: Output CONTENT
        id: CONTENT
        env:
          content: |
            [
              {
              "title": "Pull Request URL",
              "url": "${{ steps.PR.outputs.pr_url }}",
              "description": { "text": "${{ steps.formating-n.outputs.value }}" },
              "footer": { "text": "created at ${{ steps.PR.outputs.pr_created_at }}"}
              }
            ]
        run: |
          echo "content=${{ toJson(env.content) }}" >> $GITHUB_OUTPUT

      - name: Can Review PR
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          DISCORD_EMBEDS: ${{ (steps.CONTENT.outputs.content) }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Ready to review PR: ${{ steps.PR.outputs.pr_title }}"
