name: Ready To Review

on: [workflow_call, workflow_dispatch]

jobs:
  submitMessage:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          # Authetication token to access GitHub APIs. (Can be omitted by default.)
          github-token: ${{ github.token }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
          sha: ${{ github.event.pull_request.head.sha }}

      - run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"

      - run: echo "Your PR title is ${{ steps.PR.outputs.pr_title }} and its event is ${{ github.event }}"

      - name: Can Review PR
        if: steps.PR.outputs.pr_found == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          CONTENT: '{
            "title": "Pull Request URL",
            "url": "${{ steps.PR.outputs.pr_url }}"
            }'
          DISCORD_EMBEDS: ${{ toJson(env.CONTENT) }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Ready to review PR: ${{ steps.PR.outputs.pr_title }}"
