name: Ready To Review

on: [workflow_call, workflow_dispatch]

jobs:
  submitMessage:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

      - name: Can Review PR
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          CONTENT: '[
            {
            "title": "Pull Request URL",
            "url": "${{ steps.PR.outputs.pr_url }}"
            },
            {
            "footer": {
            "text": "${{github.event}}",
            }]'
          DISCORD_EMBEDS: ${{ toJson(env.CONTENT) }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Ready to review PR: ${{ steps.PR.outputs.pr_title }}"
