name: Ready To Review

on:
  workflow_call:
    inputs:
      has_failure:
        type: boolean
        description: "Has Failure"
        required: true
        default: false

jobs:
  submitMessage:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set Timezone to Taipei
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          # Authetication token to access GitHub APIs. (Can be omitted by default.)
          github-token: ${{ github.token }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
          sha: ${{ github.event.pull_request.head.sha }}

      - run: echo "${{github.event.pull_request.head}}"

      - name: Get Latest Commit Message
        id: message
        run: |
          MSG=$(git show -s --format=%s)
          ESCAPED_COMMIT_MESSAGE=$(echo "$MSG" | jq -s -R -r '@json' | sed 's/`/\\**/g')
          AUTOHR=$(git show -s --format=%an)
          echo "ESCAPED_COMMIT_MESSAGE=$ESCAPED_COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "AUTOHR=$AUTOHR" >> $GITHUB_OUTPUT

      - run: echo "${{steps.message.outputs.MSG}}"

      - name: Output CONTENT
        id: CONTENT
        run: |
          echo "content=[{\"title\": \"${{ steps.PR.outputs.pr_title }}\", \"url\": \"${{ steps.PR.outputs.pr_url }}\", \"description\": \"## Ready to review PR\",\"fields\": [{\"name\": \"Commit Message\", \"value\": \"${{ steps.message.outputs.ESCAPED_COMMIT_MESSAGE }}\"}, {\"name\": \"Owner\", \"value\": \"${{ steps.message.outputs.AUTOHR }}\"}, {\"name\": \"Trigger Actor\", \"value\": \"${{ github.triggering_actor }}\"}, {\"name\": \"Status\", \"value\": \"${{ inputs.has_failure && 'Failure' || 'Success' }}\"}], \"footer\": {\"text\": \"created at ${{steps.PR.outputs.pr_created_at }} updated at ${{ fromJson(steps.PR.outputs.pr).updated_at }}\"}}]" >> $GITHUB_OUTPUT

      - name: Can Review PR
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          DISCORD_EMBEDS: ${{ steps.CONTENT.outputs.content }}
        uses: Ilshidur/action-discord@master
        with:
          args: ""
